name: Generate Snake

on:
  schedule: # Executa automaticamente todo dia às 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite rodar manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: jwaoluckas
          outputs: dist/snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
## Contribuições
![Snake animation](https://github.com/jwaoluckas/jwaoluckas/blob/output/snake.svg)
